package:
    name: pydusa
    version: 1.15

source:
    fn: pydusa-1.15es-fftmpi-6__2016_09_07.tgz
    url: http://ncmi.bcm.edu/ncmi/software/counter_222/software_121/pydusa-1.15es-fftmpi-6__2016_09_07.tgz

build:
    number: 6
    skip: True  # [win or py3k]

requirements:
    build:
        - python
        - numpy x.x
        - openmpi
        - fftw-mpi
    run:
        - numpy x.x
        - openmpi
        - fftw-mpi

test:
  imports:
    - mpi

about:
  license: GPL-2.0
  summary: Pydusa is a package for parallel programming using Python.
