{% set branch = "py3" %}
{% set build  = 14 %}

{% set openmpi_ver  = 3 %}

package:
    name: pydusa
    version: 1.15

source:
    url: https://github.com/cryoem/pydusa/archive/{{ branch }}.tar.gz
    fn: pydusa-{{ branch }}.tar.gz

build:
    number: {{ build }}
    string: openmpi{{ openmpi_ver }}_{{ build }}
    skip: True  # [win]

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - python 3.6.*
        - numpy 1.13.*
        - openmpi  {{ openmpi_ver }}
        - fftw 3.3.8 mpi_openmpi_*
    run:
        {% for package in resolved_packages('host') %}
        - {{ package }}
        {% endfor %}

test:
  imports:
    - mpi

about:
  license: GPL-2.0
  summary: Pydusa is a package for parallel programming using Python.
