package:
    name: pydusa
    version: 1.15

source:
    fn: pydusa-1.15es-fftmpi-6__2016_09_07.tgz
    url: http://ncmi.bcm.edu/ncmi/software/counter_222/software_121/pydusa-1.15es-fftmpi-6__2016_09_07.tgz

build:
    number: 0
    skip: True  # [win]

requirements:
    build:
        - python
        - numpy 1.11.*
        - openmpi

about:
  license: GPL-2.0
  summary: Pydusa is a package for parallel programming using Python.
