{% set branch = "py3" %}

package:
    name: pydusa
    version: 1.15

source:
    url: https://github.com/cryoem/pydusa/archive/{{ branch }}.tar.gz
    fn: pydusa-{{ branch }}.tar.gz

build:
    number: 11
    skip: True  # [win]

requirements:
    build:
      - {{ compiler('c') }}
    host:
        - python 3.6.*
        - numpy 1.13.*
        - cryoem::openmpi
        - fftw-mpi
        - libcxx         4.0.1  h579ed51_0  # [osx]
    run:
      {% for package in resolved_packages('host') %}
        - {{ package }}
      {% endfor %}

test:
  imports:
    - mpi

about:
  license: GPL-2.0
  summary: Pydusa is a package for parallel programming using Python.
