{% set branch = "master" %}

package:
    name: pydusa
    version: 1.15

source:
    url: https://github.com/cryoem/pydusa/archive/{{ branch }}.tar.gz
    fn: pydusa-{{ branch }}.tar.gz

build:
    number: 11
    skip: True  # [win]

requirements:
    build:
        - python 2.7.*
        - numpy 1.13.*
        - openmpi 2.0.2
        - fftw-mpi
    run:
        - python 2.7.*
        - numpy 1.13.*
        - openmpi 2.0.2
        - fftw-mpi

test:
  imports:
    - mpi

about:
  license: GPL-2.0
  summary: Pydusa is a package for parallel programming using Python.
