travis:
  secure:
    BINSTAR_TOKEN: B6jK8GKhQvWa+QwlWM6G+I0iFSEbuPNJxdOof6lPiCEeIRqxQQRxizhdK3KoRUtbSEnOHWZEarUh0o4d3BWQfzY9bz9Etw5bAAKuMyGXZOt/vsnBnCZ8lWzVJNpNWFUnTP/Jpf7NZWLPatdQgl2WLLV+Pk5idgDvrPD/L0bQo0gWEIkgGZ/1ah4wVmkI+zSSEOTmMDsZroL6xBqH1LhhDWZA5il9EdSCtpaIqiDrCwMDDxtuEFLUjmg1KLqJDx01/497PQB+PSkrabb1SJdWnIL/xwijwP3WmWHSayKEuOtBxDwykt/vOGA0YmfYtpOdPzZL22ZsyHm2iUN0jR3QAnZnzlAnIifE++cztggLHpxuORIPOFu60zChed+dI4lnHAFPsZErdZEKITko5kDnOLydcmWrW74GDujKRm3tOcLRxVaKpw93Hqyk9cx23I+qe7MvfRO5jirnjLGhORolWutmXhS4OtowWmCZD2mF2SkaaJWOfkIOtr5bbKHoi7s1cNCxoYtGl1gz3rGgTkwlkxp9kk3P2yXw/mBWJEmlhh682SqrHZwQHi8RbfnlO6sEwoFXRHnWFi0ZfF6SxwZZ5j1asfVpsDfWGhZegzPYqix4T7PgOmkkB83toyKOuBiwkhhVSLXFwL9ceKBk4jLgBAp06yLz7v6ArxgtWO6luQs=
appveyor:
  secure:
    BINSTAR_TOKEN: OcAUZlpSDgQtX8QAIX7qr8iZhsrOWwlmuyDECE7wAYBRlvXIBJ7BbXhX/Fmz4Oib

channels:
  sources: [conda-forge, defaults, cryoem]
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: pydusa-feedstock
