travis:
  secure:
    BINSTAR_TOKEN: YbSvRAeqTfSUD27gWhb46V+yno6OV+kUbPwwrrjiiSzMHVitKUUxQ9sq84YxsKAasXy474y+EBRvv0Ftfw6D4uMP2I97eJ7ZszNT2XJtMeGESs5BtjkZ7kHr5z1LvNi7FwbdDNao2TfdyVihoDLfsZ/l5xB/5ClYKb9+4URLnk1MJgak73u0AJnsbF+Fa+N2iAU4MzYqXxVyF4Rn2LknVP2f9dR+fJU2p751K8YQwK/SfCFPMpF/QyWLAe/nfGV6Yc4CYgMA1V0Jx3mDTi4DQ7stqMHsaEebshVEynmhRtyFmXLfXvQcH2BgfXZQD/rLeEVkUL3BDszTZbVnvyKkkEhu3yWLWGZbY6TrOES3/AYbweAXU/NnQ5Y5N59UxZC9YdaUfxade7qyi1B0NfIfbE0zTwQQFgofKVdoOdtNv3Az9NmprIxQ2sH2z1oR2Wkw3LGbubDkka0Nw8VxJ6PaSEoE23vSSIm67nJTWKmVZvFSmXlbHIojX1v7/J7QV1ddcu403Lz17nEMzKcwjoZAK/4u2G4Mi42xPVP/xIE8J/wwf5j2jaHZurnzgjf7AEw9eQb5BWscqsAZSAqTpUnTTOkS/IUqS2bTr3QL/h8Eb6LMOd244pVIb9beUGF60aevvori/YiIVuJWbJGrVHRGmvZCJvok5olsduv0L9BaONI=
appveyor:
  secure:
    BINSTAR_TOKEN: 8Bbfjp64oEvOo3rnhLhXmEhGf4T+JOy+AWB0WwSXZSbFqyBlWRNbW9G8aI/2liRz

channels:
  sources: [cryoem, defaults, conda-forge]
  targets:
  - [cryoem, dev]

github:
  user_or_org: cryoem
  repo_name: pydusa-feedstock
